const projects = document.getElementById("projects").children;

// GitHub API
const API_URL = "https://api.github.com/user/45130233"

// Get basic user info
const request = new XMLHttpRequest();
request.onreadystatechange = () => {
    if (request.readyState !== 4 || request.status !== 200) return;
    const response = JSON.parse(request.responseText);
    document.getElementById("pageTitle").innerHTML = `${response["name"]}'s (autogenerated) portfolio`;
    document.getElementById("profilePic").src = response["avatar_url"];
    document.getElementById("title").innerHTML =
        `<a href=${response["html_url"]}>${response["name"]}</a>'s (autogenerated) portfolio`;
    document.getElementById("bio").innerHTML = response["bio"];

    document.getElementById("repoCount").innerHTML = `Public repos: ${response["public_repos"]}`;
    document.getElementById("followerCount").innerHTML = `Followers: ${response["followers"]}`;
    document.getElementById("codingSince").innerHTML =
        `Coding since ${new Date(response["created_at"]).getFullYear()}`;

    // Select repositories to showcase
    const repoRequest = new XMLHttpRequest();
    repoRequest.onreadystatechange = () => {
        if (repoRequest.readyState !== 4 || repoRequest.status !== 200) return;
        const response = JSON.parse(repoRequest.responseText);
        let j = 0;
        for (let i = 0; i < response.length; i++) {
            const repo = response[i];
            if (Number(repo["stargazers_count"]) + Number(repo["watchers_count"]) < 1 || repo["fork"]) continue;
            document.getElementById("projects").innerHTML += `
                 <div class="${j++ > 2 ? "hidden" : ""}">
                     <h3><a href="${repo["html_url"]}">${repo["name"]}</a></h3>
                     <p>${repo["description"] || ""}</p>
                 </div>
            `;
        }
    }
    repoRequest.open("GET", response["repos_url"], true);
    repoRequest.send(null);
}
request.open("GET", API_URL, true);
request.send(null);

const lengthMod = Math.floor(projects.length / 3);
const c1 = 3 * lengthMod + 2;
let projectIndex = 0;
function nextProjects() {
    if (projects.length < 4) return;
    if (projectIndex++ > lengthMod) projectIndex = 0;
    if (projectIndex > 0) {
        const j = 3 * projectIndex;
        for (let i = 0; i < 3; i++) {
            projects[j - i - 1]?.classList.add("hidden");
            projects[j + i]?.classList.remove("hidden");
        }
    } else {
        for (let i = 0; i < 3; i++) {
            projects[c1 - i]?.classList.add("hidden");
            projects[i].classList.remove("hidden");
        }
    } setTimeout(nextProjects, 10000);
} setTimeout(nextProjects, 10000);